"""The solver core: enumerate the word pairs, extract each sandwich's
coefficient matrix, and classify it — deciding whether
``mid^mu = A mid^mu B`` holds, on the constraint surface, exactly.

For a pair (A, B) the sandwich A mid^mu B either does not expand in the
basis (certified no-expansion) or expands with a coefficient matrix C
(C[mu][nu] = coefficient of B^nu). The identity ``= mid`` holds iff
C = I. More generally C may be a SCALAR multiple s*I; then the identity
holds iff s = 1 ON THE CONSTRAINT — decided exactly by reducing s - 1
modulo the constraint ideal (the constraint polynomial and its
conjugate), not by sampling. A non-scalar C is a genuine basis mixing
and never equals mid.

The classification is exact and symbolic; an optional numeric pass on
the constraint surface cross-checks it (defence in depth).
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import sympy as sp

from .alphabet import build_alphabet
from .expand import coefficient_matrix, trace_orthogonal_norms


@dataclass(frozen=True)
class Cell:
    a: str
    b: str
    expands: bool
    kind: str                 # "identity" | "scalar" | "matrix" | "no-expansion"
    scalar: Optional[object]  # the s in s*I when kind == "scalar"/"identity"
    holds: bool               # does mid^mu = A mid^mu B hold (on constraint)?


@dataclass(frozen=True)
class SolveResult:
    spec_name: str
    alphabet: tuple
    cells: dict               # {(a, b): Cell}

    def identities(self) -> list:
        return sorted(k for k, c in self.cells.items() if c.holds)

    def holds(self, a: str, b: str) -> bool:
        return self.cells[(a, b)].holds


def _scalar_is_one_on_constraint(s, params, constraint) -> bool:
    """Exact: is the scalar polynomial s equal to 1 on the constraint
    surface? Reduce s - 1 modulo the ideal generated by the constraint
    and its conjugate (parameters and their conjugates treated as
    independent). Uses a Groebner basis so a zero remainder is a genuine
    ideal-membership proof."""
    if sp.expand(s - 1) == 0:
        return True
    if constraint is None:
        return False
    q = sp.symbols(f"_wc0:{len(params)}", complex=True)
    subs = {sp.conjugate(params[i]): q[i] for i in range(len(params))}
    expr = sp.expand((s - 1).subs(subs))
    g = sp.expand(sp.sympify(constraint(params)).subs(subs))
    gbar = sp.expand(sp.sympify(constraint(q)))
    gens = list(params) + list(q)
    try:
        G = sp.groebner([g, gbar], *gens, order="grevlex")
        return sp.expand(G.reduce(expr)[1]) == 0
    except Exception:                                   # pragma: no cover
        # last resort: direct divisibility by the (single) constraint
        return sp.simplify(sp.rem(expr, g)) == 0


def _classify(C_rows, params, constraint):
    dim = len(C_rows)
    C = sp.Matrix(C_rows)
    s = C[0, 0]
    is_scalar_I = all(
        sp.expand(C[i, j] - (s if i == j else 0)) == 0
        for i in range(dim) for j in range(dim))
    if not is_scalar_I:
        return "matrix", None, False
    if sp.expand(s - 1) == 0:
        return "identity", sp.Integer(1), True
    return "scalar", sp.expand(s), _scalar_is_one_on_constraint(
        s, params, constraint)


def solve(spec, query: str = "identity") -> SolveResult:
    """Solve a brief: classify every (A, B) sandwich over the alphabet.

    query "identity" (spec 01): report whether mid^mu = A mid^mu B holds.
    """
    spec.validate()
    if query != "identity":
        raise ValueError("spec 01 supports query='identity' "
                         "(mid = A mid B); matrix-coefficient queries are a "
                         "later phase")
    p = spec.symbols()
    Z, Zi = spec.generator(p), spec.inverse(p)
    alphabet = build_alphabet(Z, Zi, spec.operations)
    basis = spec.mids()
    norms = trace_orthogonal_norms(basis)

    cells = {}
    for an, A in alphabet.items():
        for bn, B in alphabet.items():
            C_rows, expands = coefficient_matrix(A, basis, B, norms)
            if not expands:
                cells[(an, bn)] = Cell(an, bn, False, "no-expansion",
                                       None, False)
                continue
            kind, scalar, holds = _classify(C_rows, p, spec.constraint)
            cells[(an, bn)] = Cell(an, bn, True, kind, scalar, holds)
    return SolveResult(spec.name, tuple(alphabet), cells)
